# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=10)),
                ('area_id', models.IntegerField(default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='FlyWay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_port', models.CharField(default='XXX', max_length=3)),
                ('destination_port', models.CharField(default='XXX', max_length=3)),
                ('search_flag', models.BooleanField(default=False)),
                ('transfer_flag', models.BooleanField(default=True)),
                ('direct_flag', models.BooleanField(default=False)),
                ('lcc_flag', models.BooleanField(default=False)),
                ('old_stop', models.CharField(default='', max_length=15)),
                ('new_top', models.CharField(default='', max_length=15)),
                ('is_exist', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('is_real', models.BooleanField(default=False)),
            ],
        ),
    ]
