# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='area_id',
            field=models.IntegerField(default=0),
        ),
    ]
