# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_auto_20160512_2313'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlyWay',
            new_name='Flypath',
        ),
    ]
