# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_flightpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightpath',
            name='old_stop',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
