# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-12 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0005_auto_20160512_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_port', models.CharField(default='XXX', max_length=3)),
                ('destination_port', models.CharField(default='XXX', max_length=3)),
                ('search_flag', models.BooleanField(default=False)),
                ('transfer_flag', models.BooleanField(default=True)),
                ('direct_flag', models.BooleanField(default=False)),
                ('lcc_flag', models.BooleanField(default=False)),
                ('old_stop', models.CharField(default='', max_length=15, null=True)),
                ('new_top', models.CharField(default='', max_length=15)),
                ('is_exist', models.BooleanField(default=True)),
            ],
        ),
    ]
